services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: object-detection-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/temp_videos:/app/temp_videos
      - ./backend/outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: object-detection-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  temp_videos:
  outputs:
